card_race="human";
card_type="soldier";
card_sprite = spr_lowKnightIdle;
card_attack=3;
card_turn=3;
card_health=3;
card_name = "Human Low Knight"
card_cost = 1;
card_physical = noone;
card_object = obj_lowKnight;
startY = y;
moving = false;